In [210]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [211]:
# Create an array 'x' with 10 elements, all set to 1
x = np.ones(10)

# Print the array 'x'
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [212]:
# Create an array 'y' with 10 elements, all set to 0
y = np.zeros(10)

# Print the array 'y'
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [213]:
# Add the arrays 'x' and 'y' together
sum_array = x + y

# Print the sum of the arrays 'x' and 'y'
print(sum_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [214]:
# Print characteristics of the array 'x'
print("x array characteristics:")

# Print the shape of the array
print("Shape:", x.shape)

# Print the data type of the array elements
print("Data type:", x.dtype)

# Print the total number of elements in the array
print("Size:", x.size)

# Print the number of dimensions of the array
print("Dimensions:", x.ndim)

# Print the sum of all elements in the array
print("Sum of all numbers:", np.sum(x))

# Print the mean of the array elements
print("Mean:", np.mean(x))

# Print the standard deviation of the array elements
print("Standard deviation:", np.std(x))

x array characteristics:
Shape: (10,)
Data type: float64
Size: 10
Dimensions: 1
Sum of all numbers: 10.0
Mean: 1.0
Standard deviation: 0.0


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [215]:
# Create a 2D array 'w' with specified elements
w = np.array([[11, 12], [13, 14], [15, 16]])

# Print the 2D array 'w'
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [216]:
# 'z' array contains numbers from 1 to 3
z = np.array([1, 2, 3])

# Print the array 'z'
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [217]:
# Stack the arrays 'w' and 'z' horizontally
newArray = np.hstack((w, z.reshape(3, 1)))  # Reshape 'z' to a 3x1 array to match the dimensions of 'w'

# Print the new array
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [218]:
# Print each row of 'newArray' with a row count
count = 0
for i in newArray:
    print(f"Row {count}", i)
    count += 1

print() # for a new line 

for row in newArray:
    for element in row:
        print(element, end=' ')
    print()  # for a new line after each row

Row 0 [11 12  1]
Row 1 [13 14  2]
Row 2 [15 16  3]

11 12 1 
13 14 2 
15 16 3 


## Q#9: Reverse the columns and rows of "newArray".

In [219]:
# Reverse the columns and rows of 'newArray'
reversedArray = newArray[::-1, ::-1]

# Print the reversed array
print(reversedArray)

[[ 3 16 15]
 [ 2 14 13]
 [ 1 12 11]]


## Q#10: Decrement all elements of "newArray" with 1.

In [220]:
# Decrement all elements of 'newArray' by 1
newArray = newArray - 1

# Print the updated 'newArray'
print(newArray)

[[10 11  0]
 [12 13  1]
 [14 15  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [221]:
# Smallest and biggest in newArray

# Check if the array is empty
if newArray.size == 0:
    print("Array is empty")

else:
    smallest = newArray.min() # Find the smallest number in the array
    biggest = newArray.max() # Find the biggest number in the array

    # print the smallest and biggest
    print("Smallest:", smallest)
    print("Biggest:", biggest)

Smallest: 0
Biggest: 15


## Q#12: Print the first row of "newArray" using indexing.

In [222]:
# Print first row of 'newArray'
print("First row:", newArray[0])

First row: [10 11  0]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [223]:
# Function to print the index of a number in the array
def print_index(number, index):
    # Check if the number 12 is found in the array
    if index[0].size == 0:
        # If the number 12 is not found, print a message
        print(f"Number {number} not found in the array")
    else:
        print(f"Number equals {newArray[index][0]} is at index {index[0][0]}, {index[1][0]}")   # index[0][0] is the row index, index[1][0] is the column index

In [224]:
# Find the index of the number 12 in 'newArray'
index = np.where(newArray == 12)

# Print the index of the number 12
print_index(12, index)

Number equals 12 is at index 1, 0


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [225]:
# Find the indices of the numbers 0 and 13 in 'newArray'
index_0 = np.where(newArray == 0)
index_13 = np.where(newArray == 13)

# Print the indices of the numbers 0 and 13
print_index(0, index_0)
print_index(13, index_13)

Number equals 0 is at index 0, 2
Number equals 13 is at index 1, 1


## Q#15: Change the shape of "newArray" to (9,1).

In [226]:
# Function to reshape the array to the specified shape
def reshape_array(arr, shape):
    try:
        # Attempt to reshape the array
        arr = arr.reshape(shape)
            
        # Print the new shape of the array
        print("newArray shape:", arr.shape)

        # Print the reshaped array
        print("Reshaped newArray:")
        print(arr)
        
        return arr
    
    except ValueError:
        # If reshaping fails, print an error message and return the original array
        print(f"Cannot reshape array to {shape}")
        return arr

In [227]:
# Reshape 'newArray' to a 9x1 array
newArray = reshape_array(newArray, (9, 1))

newArray shape: (9, 1)
Reshaped newArray:
[[10]
 [11]
 [ 0]
 [12]
 [13]
 [ 1]
 [14]
 [15]
 [ 2]]


## Q#16: Change the shape of "newArray" to (3,2).

In [228]:
# Reshape 'newArray' to a 3x2 array
newArray = reshape_array(newArray, (3, 2))

Cannot reshape array to (3, 2)


# Well Done 🎉