# Q1: Import numpy library

In [92]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [93]:
# Generate a sequence of 15 floats using linspace() function
# and print the sequence
seq = np.linspace(1, 15, 15)
print(seq)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [94]:
# Create a 3-D array in shape (2, 2, 3) containing the four arrays

# Array 1
array1 = np.array([[1.1, 2.1, 3.1]])

# Array 2
array2 = np.array([[4.1, 5.1, 6.1]])

# Array 3
array3 = np.array([[7.1, 8.1, 9.1]])

# Array 4
array4 = np.array([[10.1, 11.1, 12.1]])

# Combine the four arrays into a single 3-D array and reshape it to (2, 2, 3)
array_3d = np.array([array1, array2, array3, array4]).reshape(2, 2, 3)

# Print the 3-D array
print("3-D Array:")
print(array_3d)

# Print the shape of the 3-D array
print("\nShape of the 3-D Array:")
print(array_3d.shape)

3-D Array:
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]

Shape of the 3-D Array:
(2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [95]:
# Print the type of the 3-D array
print("Type of the 3-D Array:", type(array_3d))

# Print the data type of the elements in the 3-D array
print("Data type of the 3-D Array:", array_3d.dtype)

# Print the shape of the 3-D array
print("Shape of the 3-D Array:", array_3d.shape)

# Print the size (total number of elements) of the 3-D array
print("Size of the 3-D Array:", array_3d.size)

# Print the number of dimensions of the 3-D array
print("Number of dimensions of the 3-D Array:", array_3d.ndim)

Type of the 3-D Array: <class 'numpy.ndarray'>
Data type of the 3-D Array: float64
Shape of the 3-D Array: (2, 2, 3)
Size of the 3-D Array: 12
Number of dimensions of the 3-D Array: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [96]:
# New array to hold the 4-D array
# Adding an extra dimension to the existing 3-D array
array_4d = np.array([array_3d])

# Print the dimensions of the 4-D array
print("Number of dimensions of the 4-D Array:", array_4d.ndim)

# Print the shape of the 4-D array
print("\nShape of the 4-D Array:", array_4d.shape)

# Print the 4-D array
print("\n4-D Array:")
print(array_4d)

Number of dimensions of the 4-D Array: 4

Shape of the 4-D Array: (1, 2, 2, 3)

4-D Array:
[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [97]:
# Change the type of the elements in the 4-D array to int
array_4d_int = array_4d.astype(int)

# Print the type of the elements in the 4-D array
print("Type of the 4-D Array:", array_4d_int.dtype)

# Print the 4-D array
print("\n4-D Array:")
print(array_4d_int)

Type of the 4-D Array: int32

4-D Array:
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [98]:
# Print elements of the 4-D array using nditer() function

print("Elements of the 4-D Array:")
for x in np.nditer(array_4d_int):
    print(x, end=' ')

Elements of the 4-D Array:
1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing

In [99]:
# Q8:  Print number 8 using array slicing

def print_number(arr, index):
    try:
        print(f"Number {arr[index]} found at index {index} using array slicing.")
    except IndexError:
        print("Index out of range")

In [100]:
# Print number 8 using array slicing
print_number(array_4d_int, (0, 1, 0, 1))

Number 8 found at index (0, 1, 0, 1) using array slicing.


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [101]:
# Print number 5 using array slicing
print_number(array_4d_int, (0, 0, 1, 1))

# Print number 6 using array slicing
print_number(array_4d_int, (0, 0, 1, 2))

Number 5 found at index (0, 0, 1, 1) using array slicing.
Number 6 found at index (0, 0, 1, 2) using array slicing.


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [102]:
def find_number(arr, num):
    try:
        # Use np.where() to find the index of the number in the array
        index = np.where(arr == num)
        
        # Convert the result to a more readable format
        readable_index = tuple(i[0] for i in index)
        
        # Print the result
        print(f"Number {num} found at index {readable_index} using np.where().")
    except:
        # Handle the case where the number is not found in the array
        print(f"Number {num} not found in the array.")

# Find number 8 using np.where()
find_number(array_4d_int, 8)

Number 8 found at index (0, 1, 0, 1) using np.where().


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [103]:
# Reshape array_4d_int to (2, 3, 2) 
try:
    # Attempt to reshape the array
    array_3d_2 = array_4d_int.reshape(2, 3, 2)
    
    # Print the shape of the reshaped array
    print("Shape of the 3-D Array:", array_3d_2.shape)
    
    # Print the reshaped 3-D array
    print("\n3-D Array:")
    print(array_3d_2)
    
except ValueError:
    # Handle the case where the reshape operation fails
    print("Reshape failed due to incompatible shape.")

Shape of the 3-D Array: (2, 3, 2)

3-D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [104]:
# Join the two arrays

# Create two arrays
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

# Concatenate the two arrays
arr_row = np.concatenate((arr1, arr2))

# Print the concatenated array
print("Concatenated array:")
print(arr_row)

Concatenated array:
[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [105]:
# join the two arrays along axis 1
arr_col = np.concatenate((arr1, arr2), axis=1)

# Print the concatenated array
print("Concatenated array along axis 1:")
print(arr_col)

Concatenated array along axis 1:
[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [106]:
# Split the concatenated array into two arrays along axis 1
arr1_split, arr2_split = np.split(arr_row, 2, axis=1)

# Print the two split arrays
print("Split arrays:")

# Print the first split array with its shape and size
print(f"\nFirst split array of shape: {arr1_split.shape} and size = {arr1_split.size} (arr1_split):")
print(arr1_split)

# Print the second split array with its shape and size
print("\nSecond split array of shape: {arr2_split.shape} and size = {arr2_split.size} (arr2_split):")
print(arr2_split)


Split arrays:

First split array of shape: (4, 1) and size = 4 (arr1_split):
[['A']
 ['E']
 ['C']
 ['G']]

Second split array of shape: {arr2_split.shape} and size = {arr2_split.size} (arr2_split):
[['B']
 ['F']
 ['D']
 ['H']]
